platform :ios, '18.0'  # Ensure iOS platform target is set to 16.0

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Combine both configurations into a single post_install hook
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
