# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Post install configuration to exclude arm64 for the simulator
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end
